### PR TITLE
fix: shiki -> react-syntax-highlighter 

### LINKED ISSUE #135: [BUG]: Shiki Loading Times
### Description 📝

Shiki takes a long time to load. We should migrate all code preview components to using 'react-syntax-highlighter'.

### Link 🔗

n/a

### Steps to Reproduce 🔄

1. Open our site
2. Navigate to a docs page that dispalys code
3. View the `Loading...` message

### Screenshots 📸

Screenshot 2024-05-03 at 10 09 25 AM

### Expected Behavior 🤔

It should load much quicker.

### Actual Behavior 😱

Loading taks a long time.

### Environment 🌍

N/A

### Additional Information ℹ️

_No response_

### PR DESCRIPTION
**Pull request by epoll31**
## Description

using `react-syntax-highlighter` in Code now / ComponentPreview references Code again / customizable prism theme

## Related Issue

Fixes #135 

## Proposed Changes

- Using `react-syntax-highlighter` instead of `codeToHtml` in `src/components/code/Code.tsx`
- Using `Code` instead of `react-syntax-highlighter` in `src/components/code/ComponentPreview.tsx` to only reference `react-syntax-highlighter` in one place
- `react-syntax-highlighter` uses a theme defined in `src/components/code/theme.ts`
  - theme is based on css variables in `src/styles/tailwind.css`
  - available tokens are defined at https://prismjs.com/tokens.html

## Screenshots

Screenshot 2024-05-03 at 10 57 04 AM

## Checklist

Please check the boxes that apply:

- [x] I have tested the changes locally
- [x] I ran `npm run build` and build is successful
- [x] I have added necessary documentation (if applicable)
- [x] I have updated the credits.md file (if applicable)

### CODE REVIEW

File: src/components/code/Code.tsx [hunk 1]
```diff
@@ -32,17 +35,11 @@ export default function Code({
...
-      )
-      setCode(html)
-    }
-    loadCode()
-  }, [rawCode, rawLang])
+  const lang = useMemo(
+    () => (rawLang ? rawLang.replace('language-', '') : 'plaintext'),
+    [rawLang],
+  )
+  const code = useMemo(() => rawCode.trim(), [rawCode])
```
Comment (Ansub) [inline src/components/code/Code.tsx:42]: what are these useMemo() doing?

**Comment by Ansub** [comment]
what are these useMemo() doing?

image

**Comment by epoll31** [comment]
> what are these useMemo() doing?
> 
> image
> 
> 

I used them to avoid performing those string mutations on rerenders. They are pretty simple so I don't think that they are vital, but I thought it would be better with them.

**Review by Ansub — APPROVED** [review]
