### PR TITLE
fix: Optional Preview Override for `ComponentPreview`

### LINKED ISSUE #147: [FEATURE]: Add optional preview override to ComponentPreview
### Feature Description 📝

I would love the ability to override the `preview` for the `ComponentPreview` component. 

The default preview works great for standalone components (ex: buttons, toggles, etc.).

But, for non-standalone components (ex: cards, containers, or effects) that are dependent on children to display properly, it would be beneficial to provide a preview through the `ComponentPreview` component.

### Motivation 🌟

in `src/showcase/ui-group/EffectCards.tsx` I specify a custom preview that is displayed in the card. this is because the BorderGlow effect is just a container that accepts children to be easily used for people taking the code.
```tsx
{
  id: 2,
  title: 'Border Glow',
  preview: (
    <div className="flex flex-col gap-2">
      <BorderGlow>Border Glow</BorderGlow>
      <BorderGlow>Border Glow</BorderGlow>
    </div>
  ),
  link: '/docs/effects/border-glow',
},
```

This also means that when ComponentPreview loads the component it displays as a small empty oval which is incorrect. But, if we add this optional preview then I can reference it in the docs like this:
```tsx
<ComponentPreview
  preview={
    <div className="flex flex-col gap-2">
      <BorderGlow>Border Glow</BorderGlow>
      <BorderGlow>Border Glow</BorderGlow>
    </div>
  }
  path="effects/BorderGlow"
/>
```

### Expected Behavior 🤔

```tsx
interface ComponentPreviewProps extends React.HTMLAttributes<HTMLDivElement> {
  path: string
  align?: 'center' | 'start' | 'end'
  preview?: React.ReactNode
}


const Preview = React.useMemo(() => {
    if (preview) return preview

    try {
      const Component = require(`../../showcase/${path}.tsx`).default
      return <Component />
    } catch (error) {
      console.error(`Failed to load component ${path}:`, error)
      return (
        <p className="text-muted-foreground text-sm">
          Component{' '}
          <RawCode className="bg-muted relative rounded px-[0.3rem] py-[0.2rem] font-mono text-sm">
            {path}
          </RawCode>{' '}
          not found.
        </p>
      )
    }
  }, [path, preview])
```

### Additional Information ℹ️

_No response_

### PR DESCRIPTION
**Pull request by epoll31**
## Description

This PR adds in an optional `preview` prop to `ComponentPreview` that, when supplied, will override the default import from path.

## Related Issue

Fixes #147 

## Proposed Changes

- added optional `preview` prop to `ComponentPreview` that will override the default import from the path in `src/components/code/ComponentPreview.tsx`
  - I added `preview?: React.ReactNote` to `ComponentPreviewProps`
  - I added `if (preview) return preview` in the `Preview = useMemo(...)`
    - I also added `preview` as a dependency to the `useMemo`
- minor fixes in `src/components/code/Code.tsx` to solve issues with undefined `rawCode`
  - I moved the `code = useMemo(...)` to the top of the function
  - I reference `code` instead of `rawCode` in the `inline = useMemo(...)`

## Checklist

Please check the boxes that apply:

- [x] I have tested the changes locally
- [x] I ran `npm run build` and build is successful
- [x] I have added necessary documentation (if applicable)
- [x] I have updated the credits.md file (if applicable)

### CODE REVIEW

**Comment by Ansub** [comment]
please rebase with main to resolve conflict

**Comment by epoll31** [comment]
@Ansub Just merged!

File: src/components/code/ComponentPreview.tsx
Comment (Ansub) [inline src/components/code/ComponentPreview.tsx:1]: Update the comment on this file. Keep it simple, like the existing one. Also, add a usage example, similar to the one provided for path one.

Comment (epoll31) [reply src/components/code/ComponentPreview.tsx:1]: Just added that! Thanks

File: src/components/code/ComponentPreview.tsx [hunk 1]
```diff
@@ -33,21 +34,27 @@ const formatName = (path: string) => {
  *
  * @param {string} path - The path to the component relative to `src/showcase`.
  * @param {boolean} usingFramer - Whether the component is using Framer Motion.
+ * @param {React.ReactNode} preview - Optional preview to render instead of the component.
  * Example: "components/button/3DButton"
  *
  * Usage: <ComponentPreview path="components/button/3DButton" />
+ *
```
Comment (Ansub) [inline src/components/code/ComponentPreview.tsx:41]: in both lines can you add: 

`usage with path` and `usage with preview`

and this can be changed to: 
` * @param {React.ReactNode} preview - optional preview to render a component directly instead of using path.
`

Comment (epoll31) [reply src/components/code/ComponentPreview.tsx:41]: Good idea. Just updated the documentation
