### PR TITLE
fix: BorderGlowButton only Tailwind

### LINKED ISSUE #176: [BUG]: Border Glow Button: Remove Framer Motion
### Description 📝

We are using Framer Motion for hover and tap scaling. this can be done using pure tailwind.

### Link 🔗

https://syntaxui.com/components/button/border-glow-button

### Screenshots 📸

n/a

### PR DESCRIPTION
**Pull request by 0xyosef**
## Description

fixed `BorderGlowButton` using only Tailwind .

## Related Issue

Fixes #176 

## Proposed Changes

- changed `src/showcase/components/button/BorderGlowButton.tsx` to only use tailwind
- Change : remove note  This component requires Framer Motion from `src/app/(docs)/components/button/border-glow-button/page.mdx`

## Screenshots

issus176

## Checklist

Please check the boxes that apply:

- [x] I have tested the changes locally
- [x] I ran `npm run build` and build is successful
- [x] I have added necessary documentation (if applicable)
- [x] I have updated the credits.md file (if applicable)

## Additional Context
Please provide any additional context or information about the pull request here.

### CODE REVIEW

**Comment by epoll31** [comment]
Nice Work! @0xyosef

**Comment by 0xyosef** [comment]
> Nice Work! @0xyosef

Thanks 🤩

File: src/showcase/components/button/BorderGlowButton.tsx [hunk 1]
```diff
@@ -22,16 +21,9 @@ const BorderGlowButton = () => {
   }, [])
 
   return (
-    <motion.button
-      className="relative overflow-hidden rounded-lg bg-[#e5e7eb]"
+    <button
+      className="relative overflow-hidden rounded-lg bg-[#e5e7eb] transform active:scale-95"
```
Comment (epoll31) [inline src/showcase/components/button/BorderGlowButton.tsx:25]: Can you swap `transform active:scale-95` for `transition-transform ease-in-out active:scale-90`?

This adds a transition that is similar to what it was with Framer Motion (minus the springiness).

**Review by epoll31 — COMMENTED** [review]
Great job, but it is lacking the transition that existed in the Framer Motion version.

File: src/showcase/components/button/BorderGlowButton.tsx (hunk 1 above)
Comment (0xyosef) [reply src/showcase/components/button/BorderGlowButton.tsx:25]: Okay think u I will do it .

**Comment by Ansub** [comment]
Congratulations on your first contribution @0xyosef. If you are in the SyntaxUI [Discord](https://syntaxui.com/discord), please drop me your username, and I will promote you to contributor. ✨
