### PR TITLE
fix: GradientFillButton using only Tailwind

### LINKED ISSUE #157: [ENHANCEMENT]: Gradient Fill Button Using Only Tailwind
### Description 📝

We can re-implement the Gradient Fill Button only using Tailwind instead of Tailwind and Framer Motion

### Link 🔗

https://syntaxui.com/docs/components/button/gradient-fill-button

### Steps to Reproduce 🔄

1. Go To: https://syntaxui.com/docs/components/button/gradient-fill-button

### Screenshots 📸

n/a

### Expected Behavior 🤔

It could be implemented using groups, transitions, and maybe an ease.

### Actual Behavior 😱

It uses framer motion for animation

### Environment 🌍

n/a

### Additional Information ℹ️

_No response_

### PR DESCRIPTION
**Pull request by epoll31**
## Description

I re-implemented the `GradientFillButton` using only Tailwind

## Related Issue

Fixes #157 

## Proposed Changes

- changed `src/showcase/components/button/GradientFillButton.tsx` to only use tailwind

## Screenshots

https://github.com/Ansub/SyntaxUI/assets/16091805/50a984a8-974b-410e-9562-36ab86387218

## Checklist

Please check the boxes that apply:

- [x] I have tested the changes locally
- [x] I ran `npm run build` and build is successful
- [x] I have added necessary documentation (if applicable)
- [x] I have updated the credits.md file (if applicable)

### CODE REVIEW

File: src/showcase/components/button/GradientFillButton.tsx [hunk 1]
```diff
@@ -1,40 +1,11 @@
...
-              type: 'spring',
-              stiffness: 150,
-              damping: 20,
-            }}
-            className="absolute inset-0 z-0 bg-gradient-to-t from-red-600 to-red-500"
-          />
-        )}
-      </AnimatePresence>
-    </motion.button>
+    <button className="group/button relative overflow-hidden rounded-md border border-red-500/20 bg-red-100 px-5 py-1.5 text-xs font-medium text-red-500 transition-all duration-150 hover:scale-105 hover:border-red-500 active:scale-95">
```
Comment (Ansub) [inline src/showcase/components/button/GradientFillButton.tsx:3]: can you remove hover state from here

**Comment by Ansub** [comment]
also can you remove `usingFramer` from `src/app/docs/components/button/gradient-fill-button/page.mdx`
